# Generated by Django 5.2.16 on 2026-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='subscribed', max_length=32)),
                ('source', models.CharField(default='website', max_length=80)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='newsletter_status_idx')],
            },
        ),
    ]
