# Generated by Django 5.2.16 on 2026-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_ai_governance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigovernanceevent',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='matched_rule_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='module',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='organization_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='policy_version',
            field=models.CharField(default='ai-policy-v2.0', max_length=80),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='redaction_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='request_source',
            field=models.CharField(default='api', max_length=80),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='role_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aigovernanceevent',
            name='tool_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
