from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business_core", "0002_seed_business_core_from_legacy"),
        ("crm", "0001_crm_platform"),
        ("foundation", "0003_seed_ai_platform_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("project_name", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="new")),
                ("assigned_to", models.IntegerField(blank=True, null=True)),
                ("internal_note", models.TextField(blank=True, null=True)),
                ("quoted_at", models.TextField(blank=True, null=True)),
                ("completed_at", models.TextField(blank=True, null=True)),
                ("created_at", models.TextField()),
                ("customer", models.ForeignKey(db_column="customer_id", on_delete=django.db.models.deletion.DO_NOTHING, related_name="quote_requests", to="crm.customer")),
            ],
            options={"db_table": "quote_requests", "ordering": ["-created_at", "-id"], "managed": False},
        ),
        migrations.CreateModel(
            name="QuoteFile",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("file_name", models.TextField()),
                ("file_url", models.TextField()),
                ("file_type", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.TextField()),
                ("quote_request", models.ForeignKey(db_column="quote_request_id", on_delete=django.db.models.deletion.CASCADE, related_name="files", to="sales.quoterequest")),
            ],
            options={"db_table": "quote_files", "ordering": ["id"], "managed": False},
        ),
        migrations.CreateModel(
            name="QuoteRequestItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("drawing_code", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                ("tolerance", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("material", models.ForeignKey(blank=True, db_column="material_id", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="quote_items", to="catalog.material")),
                ("product", models.ForeignKey(blank=True, db_column="product_id", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="quote_items", to="catalog.product")),
                ("quote_request", models.ForeignKey(db_column="quote_request_id", on_delete=django.db.models.deletion.CASCADE, related_name="items", to="sales.quoterequest")),
            ],
            options={"db_table": "quote_request_items", "ordering": ["id"], "managed": False},
        ),
        migrations.CreateModel(
            name="SalesLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lead_source", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(max_length=220)),
                ("contact_person", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("new", "New Lead"), ("contacted", "Contacted"), ("meeting", "Meeting"), ("quotation", "Quotation"), ("negotiation", "Negotiation"), ("won", "Won"), ("lost", "Lost")], default="new", max_length=40)),
                ("priority", models.CharField(default="medium", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_leads", to="foundation.foundationuser")),
            ],
            options={"db_table": "sales_platform_leads", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="SalesOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("probability", models.PositiveIntegerField(default=10)),
                ("expected_close_date", models.CharField(blank=True, max_length=40)),
                ("status", models.CharField(choices=[("open", "Open"), ("proposal", "Proposal"), ("negotiation", "Negotiation"), ("won", "Won"), ("lost", "Lost")], default="open", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_opportunities", to="business_core.businesscustomer")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="opportunities", to="sales.saleslead")),
                ("sales_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_opportunities", to="foundation.foundationuser")),
            ],
            options={"db_table": "sales_platform_opportunities", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="SalesQuotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quotation_number", models.CharField(max_length=80, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("approved", "Approved"), ("sent", "Sent"), ("accepted", "Accepted"), ("lost", "Lost")], default="draft", max_length=40)),
                ("approval_status", models.CharField(default="pending", max_length=40)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_quotations", to="foundation.foundationuser")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_quotations", to="business_core.businesscustomer")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotations", to="sales.salesopportunity")),
            ],
            options={"db_table": "sales_platform_quotations", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="SalesQuotationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_quote_lines", to="business_core.businessproduct")),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="sales.salesquotation")),
            ],
            options={"db_table": "sales_platform_quotation_lines", "ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="SalesFollowUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("due_date", models.CharField(blank=True, max_length=40)),
                ("status", models.CharField(default="open", max_length=40)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_follow_ups", to="business_core.businesscustomer")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="follow_ups", to="sales.saleslead")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="follow_ups", to="sales.salesopportunity")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_follow_ups", to="foundation.foundationuser")),
            ],
            options={"db_table": "sales_platform_follow_ups", "ordering": ["status", "due_date", "-id"]},
        ),
        migrations.CreateModel(
            name="SalesActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_type", models.CharField(default="note", max_length=80)),
                ("subject", models.CharField(max_length=220)),
                ("content", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_activities", to="business_core.businesscustomer")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="sales.saleslead")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="sales.salesopportunity")),
            ],
            options={"db_table": "sales_platform_activities", "ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(model_name="saleslead", index=models.Index(fields=["status"], name="sales_lead_status_idx")),
        migrations.AddIndex(model_name="saleslead", index=models.Index(fields=["priority"], name="sales_lead_priority_idx")),
        migrations.AddIndex(model_name="salesopportunity", index=models.Index(fields=["status"], name="sales_opp_status_idx")),
        migrations.AddIndex(model_name="salesopportunity", index=models.Index(fields=["expected_close_date"], name="sales_opp_close_idx")),
        migrations.AddIndex(model_name="salesquotation", index=models.Index(fields=["status"], name="sales_quote_status_idx")),
        migrations.AddIndex(model_name="salesquotation", index=models.Index(fields=["approval_status"], name="sales_quote_approval_idx")),
    ]
