# Generated by Django 5.2.16 on 2026-09-09 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0005_phase3b_master_constraints'),
        ('foundation', '0007_define_phase3b_permissions'),
        ('sales', '0001_sales_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contract', models.CharField(choices=[('LEGACY', 'Legacy'), ('MVP_V1', 'MVP V1')], db_index=True, default='MVP_V1', max_length=16)),
                ('legacy_quote_request_id', models.IntegerField(blank=True, null=True)),
                ('rfq_number', models.CharField(max_length=32)),
                ('quotation_family_number', models.CharField(blank=True, max_length=24, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('request_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_INFORMATION', 'Needs information'), ('READY_TO_QUOTE', 'Ready to quote'), ('QUOTED', 'Quoted'), ('DECLINED', 'Declined'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=24)),
                ('project_name', models.CharField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('quote_due_at', models.DateField()),
                ('required_delivery_date', models.DateField()),
                ('closure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rfqs', to='foundation.foundationuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rfqs', to='foundation.foundationuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='business_core.businesscustomer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_rfqs', to='foundation.foundationuser')),
            ],
            options={
                'db_table': 'sales_rfqs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesRfqLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('M', 'Metres'), ('MM', 'Millimetres')], default='PCS', max_length=8)),
                ('required_delivery_date', models.DateField()),
                ('tolerance', models.CharField(blank=True, max_length=120)),
                ('technical_notes', models.TextField(blank=True)),
                ('drawing_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='business_core.businessmaterial')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='business_core.businessproduct')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesrfq')),
            ],
            options={
                'db_table': 'sales_rfq_lines',
                'ordering': ['rfq_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesRfqDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_group_id', models.UUIDField(default=uuid.uuid4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512)),
                ('mime_type', models.CharField(choices=[('application/pdf', 'PDF'), ('application/step', 'STEP'), ('model/step', 'STEP model'), ('application/dxf', 'DXF'), ('image/vnd.dxf', 'DXF image'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Excel workbook')], max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('document_revision', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='sales.salesrfqdocument')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.salesrfq')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_rfq_documents', to='foundation.foundationuser')),
                ('rfq_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.salesrfqline')),
            ],
            options={
                'db_table': 'sales_rfq_documents',
                'ordering': ['rfq_id', 'document_group_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='SalesTechnicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('STARTED', 'Started'), ('NEEDS_INFORMATION', 'Needs information'), ('READY_TO_QUOTE', 'Ready to quote'), ('DECLINED', 'Declined')], max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_reviews', to='foundation.foundationuser')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_reviews', to='sales.salesrfq')),
            ],
            options={
                'db_table': 'sales_technical_reviews',
                'ordering': ['rfq_id', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesrfq',
            index=models.Index(fields=['status', 'quote_due_at'], name='sales_rfq_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrfq',
            index=models.Index(fields=['customer'], name='sales_rfq_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrfq',
            index=models.Index(fields=['assigned_to'], name='sales_rfq_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.UniqueConstraint(fields=('rfq_number',), name='uq_rfq_number'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.UniqueConstraint(condition=models.Q(('quotation_family_number__isnull', False)), fields=('quotation_family_number',), name='uq_rfq_quote_family_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uq_rfq_idempotency_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_quote_request_id__isnull', False)), fields=('legacy_quote_request_id',), name='uq_rfq_legacy_quote_id'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_contract', 'MVP_V1'), _negated=True), models.Q(('idempotency_key__isnull', True), ('request_hash__isnull', True)), models.Q(('idempotency_key__isnull', False), ('request_hash__isnull', False)), _connector='OR'), name='ck_rfq_idempotency_pair_v1'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEEDS_INFORMATION', 'READY_TO_QUOTE', 'QUOTED', 'DECLINED', 'CLOSED'])), name='ck_rfq_status'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_contract', 'MVP_V1'), _negated=True), models.Q(models.Q(('rfq_number', ''), _negated=True), ('created_by__isnull', False)), _connector='OR'), name='ck_rfq_v1_required'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.CheckConstraint(condition=models.Q(('quote_due_at__lte', models.F('required_delivery_date'))), name='ck_rfq_due_order'),
        ),
        migrations.AddConstraint(
            model_name='salesrfq',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closure_reason', ''), _negated=True), _connector='OR'), name='ck_rfq_close_reason'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqline',
            constraint=models.UniqueConstraint(fields=('rfq', 'line_number'), name='uq_rfqline_parent_number'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='ck_rfqline_number_pos'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_rfqline_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqline',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['PCS', 'KG', 'M', 'MM'])), name='ck_rfqline_unit'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqline',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='ck_rfqline_v1_required'),
        ),
        migrations.AddIndex(
            model_name='salesrfqdocument',
            index=models.Index(fields=['rfq', 'uploaded_at'], name='sales_rfqdoc_rfq_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.UniqueConstraint(fields=('document_group_id', 'version'), name='uq_rfqdoc_group_version'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.UniqueConstraint(fields=('storage_key',), name='uq_rfqdoc_storage_key'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ck_rfqdoc_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ck_rfqdoc_size_pos'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.CheckConstraint(condition=models.Q(('checksum_sha256__regex', '^[0-9a-fA-F]{64}$')), name='ck_rfqdoc_checksum_len'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type__in', ['application/pdf', 'application/step', 'model/step', 'application/dxf', 'image/vnd.dxf', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])), name='ck_rfqdoc_mime'),
        ),
        migrations.AddConstraint(
            model_name='salesrfqdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('original_filename', ''), _negated=True), models.Q(('storage_key', ''), _negated=True), models.Q(('checksum_sha256', ''), _negated=True)), name='ck_rfqdoc_v1_required'),
        ),
        migrations.AddConstraint(
            model_name='salestechnicalreview',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['STARTED', 'NEEDS_INFORMATION', 'READY_TO_QUOTE', 'DECLINED'])), name='ck_techreview_decision'),
        ),
        migrations.AddConstraint(
            model_name='salestechnicalreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision__in', ['NEEDS_INFORMATION', 'DECLINED']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='ck_techreview_reason'),
        ),
        migrations.AddIndex(
            model_name='salestechnicalreview',
            index=models.Index(fields=['rfq', 'created_at'], name='sales_techreview_rfq_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestechnicalreview',
            constraint=models.CheckConstraint(condition=models.Q(('rfq__isnull', False), ('reviewer__isnull', False)), name='ck_techreview_v1_required'),
        ),
    ]
