# Generated by Django 5.2.16 on 2026-08-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='request_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='state_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AgentToolAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('tool_name', models.CharField(max_length=120)),
                ('required_permission', models.CharField(max_length=120)),
                ('input_hash', models.CharField(max_length=64)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=32)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('policy_decision', models.CharField(default='ALLOW_READ_ONLY', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_audits', to='ai_agent.agentrun')),
            ],
            options={
                'db_table': 'ai_agent_tool_audits',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tool_name', 'status'], name='ai_tool_name_status_idx')],
            },
        ),
    ]
