# Generated by Django 5.2.16 on 2026-07-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_customer_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=220)),
                ('contact_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, default='Vietnam', max_length=120)),
                ('status', models.CharField(default='active', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_customers',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email'], name='business_customer_email_idx'), models.Index(fields=['status'], name='business_customer_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_product_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('legacy_category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('published_at', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_products',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['status'], name='business_product_status_idx'), models.Index(fields=['legacy_category_id'], name='business_product_cat_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='business_core.businessproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='business_core.inventorywarehouse')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['product_id', 'warehouse_id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=40)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business_core.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['transaction_type'], name='inventory_tx_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_item_product_wh_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'warehouse')},
        ),
    ]
