# Generated by Django 5.2.16 on 2026-09-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0002_seed_business_core_from_legacy'),
        ('foundation', '0007_define_phase3b_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contract', models.CharField(choices=[('LEGACY', 'Legacy'), ('MVP_V1', 'MVP V1')], db_index=True, default='MVP_V1', max_length=16)),
                ('legacy_material_id', models.IntegerField(blank=True, null=True)),
                ('material_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('standard', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_materials',
                'ordering': ['material_code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(choices=[('CUS', 'Customer'), ('PART', 'Part'), ('MAT', 'Material'), ('RFQ', 'RFQ'), ('QT', 'Quotation family'), ('SO', 'Sales order')], max_length=16)),
                ('period', models.CharField(max_length=16)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_number_sequences',
                'ordering': ['namespace', 'period'],
            },
        ),
        migrations.AddField(
            model_name='businesscustomer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_business_customers', to='foundation.foundationuser'),
        ),
        migrations.AddField(
            model_name='businesscustomer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='businesscustomer',
            name='data_contract',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('MVP_V1', 'MVP V1')], db_index=True, default='LEGACY', max_length=16),
        ),
        migrations.AddField(
            model_name='businesscustomer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_business_customers', to='foundation.foundationuser'),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_business_products', to='foundation.foundationuser'),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='data_contract',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('MVP_V1', 'MVP V1')], db_index=True, default='LEGACY', max_length=16),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='part_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='revision',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='technical_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='tolerance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('M', 'Metres'), ('MM', 'Millimetres')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_business_products', to='foundation.foundationuser'),
        ),
        migrations.AddIndex(
            model_name='businesscustomer',
            index=models.Index(fields=['status', 'company_name'], name='biz_customer_state_name_idx'),
        ),
        migrations.AddField(
            model_name='businessmaterial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_business_materials', to='foundation.foundationuser'),
        ),
        migrations.AddField(
            model_name='businessmaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_business_materials', to='foundation.foundationuser'),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='default_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_parts', to='business_core.businessmaterial'),
        ),
        migrations.AddIndex(
            model_name='businessproduct',
            index=models.Index(fields=['is_active', 'part_code'], name='business_part_active_code_idx'),
        ),
        migrations.AddIndex(
            model_name='businessproduct',
            index=models.Index(fields=['default_material'], name='business_part_material_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmaterial',
            index=models.Index(fields=['is_active', 'name'], name='business_material_active_idx'),
        ),
    ]
