# Generated by Django 5.2.16 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_core", "0005_phase3b_master_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMachiningEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=220)),
                ("material", models.CharField(max_length=120)),
                ("machining_type", models.CharField(max_length=120)),
                ("dimensions", models.CharField(blank=True, max_length=160)),
                ("tolerance", models.CharField(default="±0.01mm", max_length=80)),
                (
                    "surface_treatment",
                    models.CharField(default="None", max_length=120),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=60)),
                ("notes", models.TextField(blank=True)),
                (
                    "estimated_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estimated_total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("estimated_lead_time_days", models.PositiveIntegerField(default=3)),
                ("dfm_score", models.PositiveIntegerField(default=85)),
                ("dfm_analysis", models.TextField(blank=True)),
                (
                    "material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "machining_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("matched_products", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_machining_estimates",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
