# Generated by Django 5.2.16 on 2026-09-27 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0006_aimachiningestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('technology_type', models.CharField(blank=True, max_length=120)),
                ('process_category', models.CharField(blank=True, max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_capabilities',
                'ordering': ['display_order', 'title', 'id'],
                'indexes': [models.Index(fields=['status', 'is_active', 'display_order'], name='capability_public_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED'])), name='ck_capability_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='ck_capability_published_at')],
            },
        ),
        migrations.CreateModel(
            name='PublicProductProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('public_description', models.TextField(blank=True)),
                ('public_material', models.JSONField(blank=True, default=dict)),
                ('public_specifications', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('main_image', models.URLField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_projection', to='business_core.businessproduct')),
            ],
            options={
                'db_table': 'public_product_projections',
                'ordering': ['display_order', 'title', 'id'],
                'indexes': [models.Index(fields=['publication_status', 'display_order'], name='public_product_state_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('publication_status__in', ['DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED'])), name='ck_public_product_status'), models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='ck_public_product_published_at')],
            },
        ),
    ]
