# Generated by Django 5.2.16 on 2026-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledge_assistant_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeembedding',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='dimension',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='embedding_version',
            field=models.CharField(default='v1', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='indexed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='provider',
            field=models.CharField(default='development-hash-fallback', max_length=80),
        ),
    ]
