# Generated by Django 5.2.16 on 2026-07-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_business_core_from_legacy'),
        ('foundation', '0002_seed_foundation_from_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_quote_request_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('order_number', models.CharField(max_length=80, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=40)),
                ('internal_note', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quoted_at', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='foundation.foundationuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='business_core.businesscustomer')),
            ],
            options={
                'db_table': 'transaction_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_event_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('actor', models.CharField(blank=True, max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_history', to='transaction_domain.transactionorder')),
            ],
            options={
                'db_table': 'transaction_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('actor', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='transaction_domain.transactionorder')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_quote_item_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('drawing_code', models.CharField(blank=True, max_length=160)),
                ('material_name', models.CharField(blank=True, max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tolerance', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='business_core.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction_domain.transactionorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='business_core.businessproduct')),
            ],
            options={
                'db_table': 'transaction_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.CharField(max_length=40)),
                ('decision', models.CharField(default='pending', max_length=40)),
                ('requested_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='transaction_domain.transactionorder')),
            ],
            options={
                'db_table': 'workflow_approvals',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionorder',
            index=models.Index(fields=['status'], name='transaction_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionorder',
            index=models.Index(fields=['legacy_quote_request_id'], name='transaction_order_legacy_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['entity_type', 'entity_id'], name='transaction_history_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['action'], name='transaction_history_action_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['decision'], name='workflow_approval_decision_idx'),
        ),
    ]
