"""Phase 11.2 lightweight legacy database archive verification tool."""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from scripts.phase11_2_database_archive_backup import (
        DEFAULT_ARCHIVE_ROOT,
        sha256_file,
        sqlite_integrity_check,
        write_json,
    )
except ModuleNotFoundError:
    from phase11_2_database_archive_backup import (
        DEFAULT_ARCHIVE_ROOT,
        sha256_file,
        sqlite_integrity_check,
        write_json,
    )


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REVIEW_REPORT = PROJECT_ROOT / "docs" / "reviews" / "PHASE_11.2_DATABASE_ARCHIVE_REPORT.md"


def utc_now():
    """Return an ISO timestamp for audit records."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_json(path):
    """Load JSON and return payload plus validation errors."""
    json_path = Path(path)
    if not json_path.exists():
        return {}, [f"JSON file does not exist: {json_path}."]
    try:
        return json.loads(json_path.read_text(encoding="utf-8")), []
    except json.JSONDecodeError as exc:
        return {}, [f"JSON file is invalid: {json_path}: {exc}."]


def read_checksum_file(path):
    """Read the first checksum token from a .sha256 file."""
    checksum_path = Path(path)
    if not checksum_path.exists():
        return None, f"Checksum file does not exist: {checksum_path}."
    content = checksum_path.read_text(encoding="utf-8").strip()
    if not content:
        return None, f"Checksum file is empty: {checksum_path}."
    return content.split()[0], None


def sqlite_readable(path):
    """Verify SQLite can be opened in read-only mode."""
    database_path = Path(path).resolve()
    connection = sqlite3.connect(f"file:{database_path.as_posix()}?mode=ro", uri=True)
    try:
        connection.execute("SELECT name FROM sqlite_master LIMIT 1").fetchone()
        return True
    finally:
        connection.close()


def render_archive_report(result):
    """Render archive verification result as Markdown."""
    return f"""# Phase 11.2 Database Archive Report

## Backup Result

| Item | Value |
| --- | --- |
| Backup exists | `{result["checks"]["backup_exists"]}` |
| Metadata exists | `{result["checks"]["metadata_exists"]}` |
| Checksum valid | `{result["checks"]["checksum_valid"]}` |
| Archive readable | `{result["checks"]["archive_readable"]}` |
| SQLite integrity | `{result["sqlite_integrity_check"]}` |

## Verification Result

`{result["status"]}`

## Archive Location

`{result["backup_location"]}`

## Rollback Possibility

Rollback is possible when the archive remains readable and checksum verification
passes. Restore must happen to a separate restore location first and must not
overwrite the source database during this training phase.

## Safety

| Safety item | Value |
| --- | --- |
| Source database deleted | `{result["safety"]["source_database_deleted"]}` |
| Production database modified | `{result["safety"]["production_database_modified"]}` |
| Irreversible migration executed | `{result["safety"]["irreversible_migration_executed"]}` |

## Final Status

`{result["final_status"]}`
"""


def verify_archive(archive_root=None, review_report_path=None):
    """Verify the archive package generated by the backup tool."""
    root = Path(archive_root or DEFAULT_ARCHIVE_ROOT)
    metadata_path = root / "archive_metadata.json"
    manifest_path = root / "metadata" / "archive_package_manifest.json"
    verification_path = root / "reports" / "ARCHIVE_VERIFICATION_RESULT.json"

    metadata, metadata_errors = load_json(metadata_path)
    manifest, manifest_errors = load_json(manifest_path)
    errors = list(metadata_errors) + list(manifest_errors)

    backup_path = Path(manifest.get("backup_location") or metadata.get("backup_location") or "")
    checksum_path = Path(manifest.get("checksum_location") or "")
    expected_checksum, checksum_error = read_checksum_file(checksum_path) if str(checksum_path) else (None, "Checksum path missing.")
    if checksum_error:
        errors.append(checksum_error)

    backup_exists = backup_path.exists() if str(backup_path) else False
    metadata_exists = metadata_path.exists()
    checksum_valid = False
    archive_readable = False
    integrity_result = "NOT_RUN"

    if not backup_exists:
        errors.append(f"Backup file does not exist: {backup_path}.")
    else:
        actual_checksum = sha256_file(backup_path)
        checksum_valid = expected_checksum == actual_checksum
        if not checksum_valid:
            errors.append("Backup checksum does not match checksum file.")
        try:
            archive_readable = sqlite_readable(backup_path)
            integrity_result = sqlite_integrity_check(backup_path)
            if integrity_result != "ok":
                errors.append(f"SQLite integrity check failed: {integrity_result}.")
        except sqlite3.Error as exc:
            errors.append(f"SQLite archive is not readable: {exc}.")

    status = "ARCHIVE_VERIFIED" if not errors and checksum_valid and archive_readable else "ARCHIVE_FAILED"
    final_status = "DATABASE_ARCHIVE_COMPLETE" if status == "ARCHIVE_VERIFIED" else "DATABASE_ARCHIVE_FAILED"

    result = {
        "phase": "11.2",
        "created_at": utc_now(),
        "status": status,
        "final_status": final_status,
        "backup_location": str(backup_path),
        "metadata_location": str(metadata_path),
        "manifest_location": str(manifest_path),
        "checks": {
            "backup_exists": backup_exists,
            "metadata_exists": metadata_exists,
            "checksum_valid": checksum_valid,
            "archive_readable": archive_readable,
        },
        "sqlite_integrity_check": integrity_result,
        "errors": errors,
        "safety": {
            "source_database_deleted": False,
            "production_database_modified": False,
            "irreversible_migration_executed": False,
        },
    }

    if metadata_exists:
        metadata["verification_status"] = status
        metadata["backup_location"] = str(backup_path)
        metadata["verified_at"] = result["created_at"]
        write_json(metadata_path, metadata)

    write_json(verification_path, result)
    review_path = Path(review_report_path or DEFAULT_REVIEW_REPORT)
    review_path.parent.mkdir(parents=True, exist_ok=True)
    review_path.write_text(render_archive_report(result), encoding="utf-8")
    result["artifacts"] = {
        "verification": str(verification_path),
        "review_report": str(review_path),
    }
    write_json(verification_path, result)
    return result


def main():
    """Command line entrypoint."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Phase 11.2 legacy database archive verification")
    parser.add_argument("--archive-root", default=None, help="Archive root to verify.")
    parser.add_argument("--review-report", default=None, help="Markdown review report path.")
    parser.add_argument("--strict", action="store_true", help="Return non-zero when archive verification fails.")
    args = parser.parse_args()

    result = verify_archive(archive_root=args.archive_root, review_report_path=args.review_report)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    if result["status"] == "ARCHIVE_VERIFIED":
        return 0
    return 2 if args.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
