"""Clear only fictional enterprise demo data generated for local testing."""

from __future__ import annotations

import json

from django.core.management.base import BaseCommand

from apps.core.management.commands.demo_data import DemoDataCleaner


class Command(BaseCommand):
    """Remove demo records without touching real or manually-created data."""

    help = "Clear fictional MEC Precision demo data generated by generate_demo_data."

    def handle(self, *args, **options):
        """Run the cleanup command."""
        result = DemoDataCleaner().clear()
        self.stdout.write(json.dumps(result, indent=2, ensure_ascii=False))
        self.stdout.write(self.style.SUCCESS("MEC demo data cleared successfully."))
