# Generated by Django 5.2.16 on 2026-07-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'foundation_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoundationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('module', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'foundation_permissions',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='FoundationRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.foundationpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.foundationrole')),
            ],
            options={
                'db_table': 'foundation_role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='foundationrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='foundation.FoundationRolePermission', to='foundation.foundationpermission'),
        ),
        migrations.CreateModel(
            name='FoundationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('password_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_admin_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='foundation.foundationrole')),
            ],
            options={
                'db_table': 'foundation_users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FoundationUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=80)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='foundation.foundationuser')),
            ],
            options={
                'db_table': 'foundation_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='FoundationAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='foundation.foundationuser')),
            ],
            options={
                'db_table': 'foundation_auth_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='foundation_token_hash_idx'), models.Index(fields=['expires_at'], name='foundation_token_exp_idx')],
            },
        ),
    ]
