# Generated by Django 5.2.16 on 2026-08-02 04:13

# ruff: noqa: RUF012 - Django migration operations are declarative class data.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0005_add_sales_approval_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundationLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "remote_addr_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("success", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "foundation_login_attempts",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FoundationTwoFactorChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_id", models.CharField(max_length=64, unique=True)),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_challenges",
                        to="foundation.foundationuser",
                    ),
                ),
            ],
            options={
                "db_table": "foundation_two_factor_challenges",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["challenge_id", "expires_at"],
                        name="foundation_2fa_lookup_idx",
                    )
                ],
            },
        ),
    ]
